server:
  port: 8000
  servlet:
    context-path: /blog
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

# static 이하는 정적파일(브라우저가 인식할수 있는것만 넣어야함) 
# 그냥 static에 test.jsp이런식으로 파일 넣어놓고 컨트롤러 클래스 가서
# 매핑 시켜도 주소 치면 못참음 왜?
# jsp는 동적인 파일이기 떄문(자바파일이고 컴파일이 일어나야함) 그래서 브라우저가 인식을 못함
# 그래서 경로를 좀 바꿔야함 아래쪽 main에 webapp/WEB-INF/views
# 저 위에 prefix라는건 컨트롤러가 리턴할때 앞에 붙여주는 경로명
# suffix는 뒤에 붙여주는 경로명


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Seoul
    username: hydev
    password: 1234
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update # 이걸 update라고도 할 수도 있고 none 이라고도 할 수 있음 create는 테이블을 새로 만든다는거(플젝을 실행할때마다) 최초에만 create로 하고 나중엔 update로 바꿔야함 안그러면 실행될때마다 create돼서 데이터 다날라감
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl # 엔티티 클래스(테이블)를 만들때 변수명 그대로 데이터베이스에 필드를 넣어줌(id,username,email,role,password~) 이거 안쓰고 
        #org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStragegy 이거 쓰면 카멜표기법 ex)myEmail 이게 필드 만들어질때 my_email 이런식으로 만들어짐
      use-new-id-generator-mappings: false # mysql로 말하면 오토 인크리즈, 오라클은 시퀀스를 어케 사용할건지 말하는거 false는 jpa가 사용하는 기본 넘버링을 사용하지 않는다는거 이렇게 안하고 generation.value 에서 strategy 설정했음
    show-sql: true # sql 쿼리 로그 보임
    properties:
      hibernate.format_sql: true # 이거 true하면 로그가 여러줄로 정렬되어서 예쁘게 나옴

  jackson:
    serialization:
      fail-on-empty-beans: false